### ISSUE TITLE
Usage in a CI/CD pipeline with a Github action

### ISSUE THREAD

**Issue by clemlatz** [B1NARY-GR0UP/nwa#6]
**Is your feature request related to a problem? Please describe.**

When new files are added to a project in a pull request, they might not have the correct header.

**Describe the solution you'd like**

A configuration GitHub action that would execute `nwa check` against any pull request in a project to ensure headers are present in every files.

**Describe alternatives you've considered**

Executing nwa manually for every pull request 😞

**Additional context**

Now that all my code source files have a header thanks to nwa 🥳, I want to ensure future contributions also include it in new files (or doesn't accidentally delete it in existing ones). I've started thinking about creating a Github action, but maybe you already have one, or have already solved this issue in some other way.

**Comment by justlorain** [comment]
This is a great idea, and many projects also have a license header check action like this. I will try adding this feature. I just looked into it and found it’s not very difficult.

I’m glad to hear that nwa is working well in your repo. This is a milestone for nwa 🥳

**Comment by clemlatz** [comment]
Hey, it's a great start, thanks !

Although I've noticed that the GitHub action won't fail if nwa detects a missing header, which I think it should to make this GitHub action relevant and prevent merging pull requests with missing headers.

This can been seen [in this workflow run](https://github.com/B1NARY-GR0UP/nwa/actions/runs/11725738770/job/32662746104#step:7:13) where nwa logs `INFO file does not have a matched header path=./util/header.go` but the workflow still passes successfully.

It thinks this is because nwa does not return an error non-zero exit code when a file is missing a header. I could reproduce this locally by creating an empty html file and running nwa against it.

<img width="1083" alt="Capture d’écran 2024-11-08 à 21 39 17" src="https://github.com/user-attachments/assets/4b46bbe5-58da-4fc6-a4f1-d67442c1e45c">

**Comment by justlorain** [comment]
**Good point!**

The latest commit already supports this, and you can use the following CI to test:

```yaml
name: Pull Request Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install NWA
        run: go install github.com/B1NARY-GR0UP/nwa@c1ec32a9d490e77e7399a59f4d3eb6a23f352bec

      - name: Run License Header Check
        run: nwa check -c "BINARY Members" -l apache ./**/*.go ./*.go
```

**Examples**

- Successful CI: https://github.com/rainiring/test/actions/runs/11752114796/job/32743198081
- Failed CI: https://github.com/rainiring/test/actions/runs/11752122980/job/32743220912

I will release a new version after I complete the fuzzy matching feature. For now, it’s feasible to use the commit version specified in the CI example above, and the Docker image version is consistent with the latest commit on the main branch.
